site_name: Snapr - Documentation Hub
nav:
  - ğŸ  Home: index.md
  - ğŸ“ Changelog: CHANGELOG.md
  - ğŸ§‘â€ğŸ’» Functional Documentation:
    - ğŸ” Overview: functional/overview.md
    - ğŸš¶â€â™€ï¸ User Flow: functional/user-flow.md
    - âœ¨ Features: functional/features.md
    - ğŸ¨ UI: functional/ui.md
    - âš ï¸ Limitations: functional/limitations.md
    - ğŸš€ Future Features: functional/future-features.md
  - ğŸ›  Technical Documentation:
    - ğŸ§± Architecture: technical/architecture.md
    - ğŸ¤– AI Agents: technical/agents.md
    - ğŸ§  ML Models: technical/models.md
    - ğŸ—‚ï¸ Data Pipeline: technical/data.md
    - ğŸ”Œ API Reference: technical/api.md
    - âš™ï¸ Local Dev: technical/localdev.md
    - ğŸ” CI/CD Workflow: technical/cicd.md
    - ğŸš€ Deployment: technical/deployment.md
    - ğŸ› ï¸ Troubleshooting: technical/troubleshooting.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    # - toc.integrate
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    # Light mode
    - scheme: default
      primary: orange
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: orange
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
docs_dir: docs
extra_css:
  - styles/colors.css
plugins:
  - search
  - glightbox
  - macros:
      module_name: mkdocs_macros
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: false
      toc_depth: 0
repo_url: https://github.com/lisekarimi/snapr
repo_name: lisekarimi/snapr
copyright: "Made with â¤ï¸ and Material for MkDocs Â· Powered by all-nighters and enthusiasm ğŸš€âœ¨"
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/lisekarimi
    - icon: fontawesome/brands/github
      link: https://github.com/lisekarimi
    - icon: fontawesome/solid/envelope
      link: mailto:lisekarimi@gmail.com
